/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.example.xmleditor.ide


/**
 * Use this class to register ide components.
 */
class XmlIdeModule extends AbstractXmlIdeModule {
}
