/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.example.xmleditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XmlRuntimeModule extends AbstractXmlRuntimeModule {
}
