/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.example.xmleditor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XmlStandaloneSetup extends XmlStandaloneSetupGenerated {

	def static void doSetup() {
		new XmlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
