/*
 * generated by Xtext 2.22.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
