/*
 * generated by Xtext 2.22.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.example.mydsl.myDsl.Greeting;
import org.xtext.example.mydsl.myDsl.WelcomeWord;
import org.xtext.example.mydsl.validation.MyDslValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class MyDslQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(MyDslValidator.INVALID_WELCOME_WORD)
	public void fixInvalidWelcomeWord(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.acceptMulti(issue, "Change to 'Hello'", "Change to 'Hello'.", "upcase.png",
			(Greeting greeting) -> { greeting.setWelcomeWord(WelcomeWord.HELLO); });
	}

}
