/*
 * generated by Xtext 2.22.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.xtext.example.mydsl.IGreetingNamesProvider;

import com.google.inject.Inject;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {

	@Inject
	private IGreetingNamesProvider greetingNamesProvider;
	
	@Override
	public void completeGreeting_Name(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeGreeting_Name(model, assignment, context, acceptor);
		for (String greetingName : greetingNamesProvider.getNames()) {
			acceptor.accept(createCompletionProposal(greetingName, context));
		}
	}
}
