/*
 * generated by Xtext 2.22.0-SNAPSHOT
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.myDsl.Greeting;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.WelcomeWord;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslValidator extends AbstractMyDslValidator {
	
	public static final String INVALID_WELCOME_WORD = "invalidWelcomeWord";

	@Check
	public void checkWelcomeWord(Greeting greeting) {
		if (greeting.getWelcomeWord() == WelcomeWord.HALLO) {
			warning("Welcome word should be in english!", MyDslPackage.Literals.GREETING__WELCOME_WORD, INVALID_WELCOME_WORD);
		}
	}
	
}
