/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.example.xmleditor.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XmlUiModule extends AbstractXmlUiModule {
}
